# Zeilen: kapitel, ka, minuten, aufgabe, teil, typ, eintrag, einheit, kette_sprosse, form, sicher(ja/einheit/nein)
KE="kein Eintrag"
R=[
# Kap 1 Reelle Zahlen
(1,1,45,1,"a-c","Am Zahlenstrahl mit Zirkel abgetragene Diagonale als Wurzel (irrationale Zahl) benennen","reelle-zahlen","E1","Zahlbereiche und irrationale Zahlen (Sprosse unsicher)","Ablesen","einheit"),
(1,1,45,2,"a-b","Potenzterme mit negativen Exponenten und Brüchen nach Potenzgesetzen umformen","reelle-zahlen","E2","Potenzgesetze","Rechnen","einheit"),
(1,1,45,2,"c","Potenzterm mit rationalen Exponenten umformen","reelle-zahlen","E3","Wurzelgesetze und rationale Exponenten","Rechnen","einheit"),
(1,1,45,3,"a-c","Wurzeln zusammenfassen, n-te Wurzeln teilen und multiplizieren","reelle-zahlen","E3","Wurzelgesetze und rationale Exponenten","Rechnen","einheit"),
(1,1,45,4,"a-d","Wurzelterme mit Variablen vereinfachen und Definitionsmenge angeben","reelle-zahlen","E3","Wurzelgesetze (Definitionsmenge fehlt im Katalog)","Rechnen","einheit"),
(1,1,45,5,"","Wurzel aus fünf durch Intervallschachtelung nähern, Halbierungsverfahren deuten","reelle-zahlen","E1","Vorschlag: Sprosse Intervallschachtelung (Katalog: H/Kl. 10)","Rechnen + Begründen","nein"),
# Kap 2 LGS
(2,1,45,1,"a-b","Lineare Gleichung mit Klammern auf beiden Seiten lösen","lineare-gleichungen","E3","x beidseitig: Klammer","Rechnen","ja"),
(2,1,45,2,"","Ungleichung aus Text aufstellen und lösen",KE,"–","Vorschlag: lineare-gleichungen E4 um Ungleichungen erweitern","Sachaufgabe","nein"),
(2,1,45,3,"a-c","Lösungsanzahl eines LGS grafisch entscheiden (keine, eine, unendlich viele)","lineare-gleichungssysteme","E1","Grafisch: Sonderfälle parallel und identisch","Zeichnen","ja"),
(2,1,45,4,"","Preis aus zwei Paketangeboten (Gerät plus Rohlinge) per LGS","lineare-gleichungssysteme","E4","Sachaufgaben (Anzahl und Preis)","Sachaufgabe","einheit"),
(2,1,45,5,"a-d","Ungleichungssystem zu gezeichneter Lösungsmenge (Halbebene) angeben",KE,"–","Vorschlag: lineare Ungleichungssysteme (Halbebenen) – Katalog nur Sek II","Umkehrung","nein"),
(2,1,45,6,"","LGS mit drei Variablen lösen","lineare-gleichungssysteme","E5","Drei Variablen (Sek II)","Rechnen","einheit"),
(2,2,60,7,"a-f","Lineare Gleichung mit zwei Variablen erkennen, in ax + by = c bringen, a, b, c ablesen","lineare-gleichungssysteme","E1","Gleichungen mit zwei Variablen (Sprosse unsicher)","Ankreuzen + Umformen","einheit"),
(2,2,60,8,"a","LGS mit dem Einsetzungsverfahren lösen","lineare-gleichungssysteme","E2","Einsetzungsverfahren (keine Kette im Kompakt)","Rechnen","einheit"),
(2,2,60,8,"b","LGS mit dem Gleichsetzungsverfahren lösen","lineare-gleichungssysteme","E2","Gleichsetzen nur im Text erwähnt; Vorschlag: Sprosse in E2","Rechnen","einheit"),
(2,2,60,9,"","Lösung aus Nr. 8 grafisch prüfen (zwei Geraden, Schnittpunkt)","lineare-gleichungssysteme","E1","Grafisch: zwei Geraden zeichnen und Schnittpunkt ablesen","Zeichnen","ja"),
(2,2,60,10,"","Zusammenhang Lösung des LGS und Lage der Geraden erläutern","lineare-gleichungssysteme","E1","Grafisch (Sprosse unsicher)","Begründen","einheit"),
(2,2,60,11,"a","Geeignetes Lösungsverfahren wählen und notieren","lineare-gleichungssysteme","E3","Additionsverfahren: Verfahren wählen","Begründen","einheit"),
(2,2,60,11,"b","LGS rechnerisch und zeichnerisch lösen","lineare-gleichungssysteme","E3","Addition/Grafisch","Rechnen + Zeichnen","einheit"),
(2,2,60,12,"","Zeigen, dass ein 3x3-System genau eine Lösung hat","lineare-gleichungssysteme","E5","Drei Variablen und Lösungsvielfalt","Rechnen + Begründen","einheit"),
(2,2,60,13,"","Ganzzahlige Lösungspaare eines Ungleichungssystems zeichnerisch bestimmen",KE,"–","Vorschlag wie Kap. 2 Nr. 5","Zeichnen","nein"),
(2,2,60,14,"a","Ziffernrätsel: zwei Gleichungen aufstellen","lineare-gleichungssysteme","E4","Sachaufgaben: Gleichungen aufstellen, nicht lösen","Sachaufgabe","ja"),
(2,2,60,14,"b-c","Ziffernrätsel per Einsetzen lösen, Zahl angeben","lineare-gleichungssysteme","E2","Einsetzungsverfahren","Rechnen","einheit"),
# Kap 3 Quadratische Funktionen
(3,1,90,1,"a-b","Graph von -x² und 0,5x² zeichnen","quadratische-funktionen","E1","Normalparabel und Streckfaktor: Wertetabelle zu a·x², Öffnung und Breite","Zeichnen","ja"),
(3,1,90,1,"c","Graph einer Scheitelpunktform mit Faktor -1 zeichnen","quadratische-funktionen","E2","Scheitelpunktform: Parabel aus der Gleichung skizzieren","Zeichnen","ja"),
(3,1,90,2,"","Zur Beschreibung (gestaucht, nach unten, verschoben) Gleichung ankreuzen","quadratische-funktionen","E2","Scheitelpunktform mit Streckfaktor (Sprosse unsicher)","Ankreuzen","einheit"),
(3,1,90,3,"","Vier Parabeln ihren Gleichungen zuordnen (Scheitel- und allgemeine Form)","quadratische-funktionen","E2","Scheitelpunktform: Scheitel am Graphen ablesen","Zuordnen","einheit"),
(3,1,90,4,"a-c","Scheitel aus Scheitelpunktform ablesen (auch Wurzel, Parameter), Lage beschreiben","quadratische-funktionen","E2","Scheitelpunktform: Scheitel aus der Scheitelpunktform ablesen, d oder e negativ","Rechnen + Beschreiben","ja"),
(3,1,90,5,"a-c","Normal-/allgemeine Form per quadratischer Ergänzung in Scheitelpunktform","quadratische-funktionen","E3","quadratische Ergänzung im Katalog nur H/binomische-formeln; Vorschlag: Sprosse in E3","Umformen","nein"),
(3,1,90,6,"a-e","Verschiebung/Spiegelung von Wurzel- und Potenzfunktionen ankreuzen",KE,"–","Vorschlag: Eintrag Potenz- und Wurzelfunktionen (Katalog: Oberstufe)","Ankreuzen","nein"),
(3,1,90,7,"","Spannweite eines Brückenbogens (Nullstellen von a·x² + e) im Kontext","quadratische-funktionen","E4","Nullstellen aus der Scheitelpunktform durch Wurzelziehen","Sachaufgabe","ja"),
(3,1,90,8,"","Extremwertaufgabe Gehege an Hauswand (Fläche maximieren)",KE,"–","Vorschlag: quadratische-funktionen E2/E4 Sprosse Extremwert (Scheitel als Maximum)","Sachaufgabe","nein"),
(3,2,60,9,"a-e","Funktion als quadratisch, linear oder keins einordnen","quadratische-funktionen","E1","Normalparabel: Gerade oder Parabel ankreuzen (Vorstufe)","Zuordnen","ja"),
(3,2,60,10,"a-c","Graphen über Wertetabelle zeichnen","quadratische-funktionen","E1","Wertetabelle zu a·x² ausfüllen, Punkte eintragen","Zeichnen","ja"),
(3,2,60,11,"a-c","Rakete: Höchstpunkt, Zeit und Funktionswert am Graphen ablesen","quadratische-funktionen","E2","Scheitel am Graphen ablesen","Ablesen","ja"),
(3,2,60,11,"d","Scheitelpunktform mit Streckfaktor aus dem Graphen bestimmen","quadratische-funktionen","E2","Gleichung aus dem Graphen aufstellen","Umkehrung","ja"),
(3,2,60,12,"a","Allgemeine Form in Scheitelpunktform (quadratische Ergänzung)","quadratische-funktionen","E3","wie Kap. 3 Nr. 5","Umformen","nein"),
(3,2,60,12,"b-c","Verlauf gegenüber Normalparabel beschreiben, mit Wertetabelle zeichnen","quadratische-funktionen","E1","Öffnung und Breite an a erkennen","Beschreiben + Zeichnen","einheit"),
(3,2,60,13,"a-e","Graphen (auch Gerade, Konstante) Funktionsvorschriften zuordnen","quadratische-funktionen","E2","Scheitelpunktform (Zuordnung)","Zuordnen","einheit"),
(3,2,60,14,"a-b","Funktionsgleichungen zweier Parabeln aus dem Graphen bestimmen, Ablesbares nennen","quadratische-funktionen","E2","Gleichung aus dem Graphen aufstellen","Umkehrung","ja"),
(3,3,55,15,"a-f","Wurzelfunktion: Graph, Definitionsbereich, Spiegelung, Streckung und Verschiebung",KE,"–","Vorschlag wie Kap. 3 Nr. 6","Zeichnen + Rechnen","nein"),
(3,3,55,16,"a-d","Scheitelpunktform ausmultiplizieren, vorher Zielform benennen","quadratische-funktionen","E3","Normalform: Scheitelpunktform ausmultiplizieren","Umformen","ja"),
(3,3,55,17,"a-b","Nullstellen aus Normal-/allgemeiner Form (p-q-Formel)","quadratische-funktionen","E4","Nullstellen aus der Normalform mit der p-q-Formel","Rechnen","ja"),
(3,3,55,17,"c","Nullstellen aus Produktform ablesen","quadratische-gleichungen","E3","Nullprodukt: Produktform, jeden Faktor null setzen","Rechnen","ja"),
(3,3,55,18,"a-c","Scheitelpunkt aus Normal-, allgemeiner und Produktform bestimmen","quadratische-funktionen","E3","Scheitel einer Normalform-Parabel (rechnerisch; Sprosse unsicher)","Rechnen","einheit"),
(3,3,55,19,"a-d","Monotonieverhalten an Graphen bestimmen",KE,"–","Vorschlag: quadratische-funktionen E1 Eigenschaften um Monotonie (steigt/fällt) ergänzen","Ablesen","nein"),
(3,3,55,20,"","Extremwertaufgabe Rechteck im dreieckigen Acker rechnerisch",KE,"–","Vorschlag wie Kap. 3 Nr. 8","Sachaufgabe","nein"),
# Kap 4 Quadratische Gleichungen (aus abgleich-quadratische-gleichungen-duden9.md)
(4,1,90,1,"a-c","Reinquadratisch lösen, auch Produkt (x−a)(x+a) und ohne Lösung","quadratische-gleichungen","E1","Wurzelziehen und Lösbarkeit: x² = c, a·x² + b = 0","Rechnen","ja"),
(4,1,90,2,"","Ausgangsgleichung aus Lösungsmenge notieren","quadratische-gleichungen","E1","Umkehrung (Sprosse unsicher)","Umkehrung","einheit"),
(4,1,90,3,"","Durch Ausklammern lösen, auch Bruchvorzahl","quadratische-gleichungen","E3","Nullprodukt: x·(x + a) = 0","Rechnen","ja"),
(4,1,90,4,"","Binomisch lösbare ankreuzen, dann quadratische Ergänzung und p-q-Formel","quadratische-gleichungen","E2","p-q-Formel (quadratische Ergänzung nicht im Katalog)","Ankreuzen + Rechnen","einheit"),
(4,1,90,5,"","In Produktdarstellung (Linearfaktoren) umformen","quadratische-gleichungen","E3","Linearfaktoren nur H; Vorschlag: Umkehrsprosse in E3","Umformen","nein"),
(4,1,90,6,"","Lösungsmenge mit Satz von Vieta (Tabelle)","quadratische-gleichungen","E2","Vieta nur als Probe/Vorrat erwähnt","Rechnen","nein"),
(4,1,90,7,"","Quadratische Gleichung zeichnerisch lösen","quadratische-funktionen","E4","Schnittpunkte (Parabel und Gerade)","Zeichnen","einheit"),
(4,1,90,8,"","Bruchgleichung: Nenner faktorisieren, Definitionsmenge, Hauptnenner, lösen",KE,"–","Vorschlag: Bruchgleichungen (Katalog: nicht aufgenommen)","Lückentext + Rechnen","nein"),
(4,1,90,9,"","Wurzelgleichung mit zwei Wurzeln",KE,"–","Vorschlag: Wurzelgleichungen (Katalog: H, nicht aufgenommen)","Rechnen","nein"),
(4,1,90,10,"","Ungleichung mit Parameter: Fälle, Intervalle",KE,"–","Vorschlag: quadratische Ungleichungen","Begründen","nein"),
(4,2,60,11,"a-c","In die Normalform umformen (Dezimal- und Bruchvorzahl)","quadratische-gleichungen","E2","Normalform: Normieren","Umformen","ja"),
(4,2,60,12,"","Geschicktesten Rechenweg ankreuzen, dann lösen","quadratische-gleichungen","E2","Verfahren wählen (Sprosse unsicher)","Ankreuzen + Rechnen","einheit"),
(4,2,60,13,"","Verschobene Normalparabel: zweite Nullstelle, Funktionsgleichung","quadratische-funktionen","E4","Nullstellen und Scheitelpunktform","Ablesen + Rechnen","einheit"),
(4,2,60,14,"","Bruch- und Wurzelgleichungen: Definitions- und Lösungsmenge",KE,"–","wie Kap. 4 Nr. 8/9","Rechnen","nein"),
(4,2,60,15,"","Lösungsmenge einer quadratischen Ungleichung am Graphen",KE,"–","wie Kap. 4 Nr. 10","Ablesen","nein"),
(4,2,60,16,"","Schnittpunkte Gerade und Parabel rechnerisch","quadratische-funktionen","E4","Schnittpunkte berechnen","Rechnen","ja"),
(4,2,60,17,"","Quadratische Ungleichung lösen, Parabel zeichnen, Lösung markieren",KE,"–","wie Kap. 4 Nr. 10","Rechnen + Zeichnen","nein"),
(4,3,80,18,"a-d","Gemischt quadratische Gleichungen lösen (Wurzel im Faktor, Minus vor x²)","quadratische-gleichungen","E2","p-q-Formel / Nullprodukt","Rechnen","einheit"),
(4,3,80,19,"","Parameter: Fallunterscheidung über die Diskriminante","quadratische-gleichungen","E2","Lösbarkeit über die Diskriminante (Gymnasium)","Lückengerüst + Begründen","einheit"),
(4,3,80,20,"","Fälle aus Nr. 19 für drei Werte prüfen","quadratische-gleichungen","E2","Lösbarkeit über die Diskriminante","Rechnen","einheit"),
(4,3,80,21,"","p-q-Formel, Nullstellen, Scheitel, zeichnen, Bedeutung der Diskriminante","quadratische-funktionen","E4","Nullstellen; Zahl der Nullstellen begründen","Rechnen + Zeichnen + Begründen","einheit"),
(4,3,80,22,"","Garten mit Weg ringsum, Wegfläche gegeben","quadratische-gleichungen","E4","Sachaufgaben: Rechteck mit Seitenbeziehung und Fläche","Sachaufgabe","einheit"),
(4,3,80,23,"","p, q notieren, Lösungen mit Vieta","quadratische-gleichungen","E2","wie Kap. 4 Nr. 6","Tabelle","nein"),
(4,3,80,24,"","Terme aus Nr. 23 in Linearfaktoren zerlegen","quadratische-gleichungen","E3","wie Kap. 4 Nr. 5","Umformen","nein"),
(4,3,80,25,"","Zaun 80 m, Fläche höchstens 300 m²: Bedingungen für die Seiten","quadratische-gleichungen","E4","Sachaufgabe mit Ungleichung; Vorschlag wie Nr. 10","Sachaufgabe","nein"),
# Kap 5 Strahlensätze
(5,1,45,1,"","Streckfaktor/Maßstab aus Original- und Bildlänge (Einheiten umrechnen)","strahlensaetze","E1","Maßstab umrechnen (Sprosse unsicher)","Rechnen","einheit"),
(5,1,45,2,"a-b","Maßstab 1:50000: Karte in Wirklichkeit und zurück","strahlensaetze","E1","Maßstab umrechnen: mal / geteilt","Rechnen","ja"),
(5,1,45,3,"","Zwei Längen in der V-Figur mit Strahlensätzen berechnen, zeichnerisch prüfen","strahlensaetze","E3","Strahlensätze: erster und zweiter Strahlensatz in der V-Figur","Rechnen + Zeichnen","ja"),
(5,1,45,4,"a-c","Strecke mit Zirkel und Lineal in gleiche Teile und im Verhältnis teilen",KE,"–","Vorschlag: strahlensaetze E3 Sprosse Streckenteilung","Konstruieren","nein"),
(5,1,45,5,"a-c","Vergrößerungsfaktor aus Negativ- und Abzugformaten","strahlensaetze","E2","Zentrische Streckung: Streckfaktor bestimmen","Rechnen","einheit"),
(5,1,45,6,"a-c","Aussagen über Bilder bei zentrischer Streckung prüfen","strahlensaetze","E2","Zentrische Streckung und Ähnlichkeit","Begründen","einheit"),
(5,1,45,7,"","Ähnliches Dreieck mit k = 3 zeichnen, Seitenlängen bestimmen","strahlensaetze","E2","Ähnlichkeit (Sprosse unsicher)","Zeichnen + Rechnen","einheit"),
(5,2,45,8,"","Maßstab einer Karte aus Fahrstrecke und Kartenlänge","strahlensaetze","E1","Maßstab umrechnen","Sachaufgabe","einheit"),
(5,2,45,9,"","Baumhöhe über Schattenlängen (Strahlensatz), Wette entscheiden","strahlensaetze","E3","Strahlensätze im Sachzusammenhang","Sachaufgabe","einheit"),
(5,2,45,10,"","Flächeninhalt von Original und Bild bei k = 3, zwei Wege","strahlensaetze","E2","Flächen bei Streckung (k²) – Sprosse unsicher","Rechnen","einheit"),
(5,2,45,11,"","Fehlende Seite eines ähnlichen Rechtecks","strahlensaetze","E2","Ähnlichkeit","Rechnen","einheit"),
(5,2,45,12,"a-b","Dreiecke auf Ähnlichkeit untersuchen und begründen","strahlensaetze","E2","Zentrische Streckung und Ähnlichkeit: Gleiche Form?","Begründen","einheit"),
(5,2,45,13,"","Bedingung für Ähnlichkeit von Rechteck und halbem Rechteck","strahlensaetze","E2","Ähnlichkeit","Begründen","einheit"),
(5,3,45,14,"a-d","Strahlensatz-Verhältnisse an einer Figur ergänzen","strahlensaetze","E3","Strahlensätze: Verhältnisse aufstellen","Lückentext","einheit"),
(5,3,45,15,"a-b","Entfernung mit Daumensprung (Strahlensatz) bestimmen","strahlensaetze","E3","Strahlensätze im Sachzusammenhang","Sachaufgabe","einheit"),
(5,3,45,16,"","Zentrische Streckung im Koordinatensystem, Streckfaktor aus Bildpunkt","strahlensaetze","E2","Zentrische Streckung","Zeichnen + Rechnen","einheit"),
(5,3,45,17,"a","Dia-Projektion: Abstand Leinwand–Projektor","strahlensaetze","E3","Strahlensätze im Sachzusammenhang","Sachaufgabe","einheit"),
(5,3,45,17,"b-d","Dia-Projektion: Flächenfaktor und Flächenverhältnis","strahlensaetze","E2","Flächen bei Streckung (k²)","Sachaufgabe","einheit"),
(5,3,45,18,"a-c","Flächenverhältnis ähnlicher Vielecke, Rolle von k","strahlensaetze","E2","Flächen bei Streckung (k²)","Rechnen + Begründen","einheit"),
# Kap 6 Pythagoras
(6,1,45,1,"a","Hypotenuse in Figur berechnen, eine Nachkommastelle","pythagoras","E1","Hypotenuse: Wurzel geht nicht auf","Rechnen","ja"),
(6,1,45,1,"b-c","Kathete in Figur berechnen (Dreieck, Rechteckdiagonale)","pythagoras","E2","Kathete: Näherungswert","Rechnen","ja"),
(6,1,45,1,"d","Höhe im gleichseitigen Dreieck","pythagoras","E3","Figuren: Höhe im gleichschenkligen Dreieck","Rechnen","ja"),
(6,1,45,2,"a-b","Kathete berechnen, Dreieck zur Kontrolle konstruieren","pythagoras","E2","Kathete: Gleichung umstellen","Rechnen + Konstruieren","ja"),
(6,1,45,2,"c-d","Katheten mit Hypotenusenabschnitt q (Kathetensatz)",KE,"–","Kathetensatz/Höhensatz im Katalog ausgeschlossen (weder RLP noch P10)","Rechnen","nein"),
(6,1,45,3,"","Höhe einer aufgeklappten Trittleiter","pythagoras","E3","Höhe im gleichschenkligen Dreieck aus Schenkel und halber Grundseite","Sachaufgabe","ja"),
(6,1,45,4,"a-d","Dreieck per Rechnung auf Rechtwinkligkeit prüfen","pythagoras","E2","Kathete und Umkehrung","Begründen","einheit"),
(6,1,45,5,"","Umfang und Fläche einer Raute aus den Diagonalen","pythagoras","E3","Figuren (Raute; Sprosse unsicher)","Rechnen","einheit"),
(6,1,45,6,"","Würfel: Volumen und Oberfläche aus Raumdiagonale","pythagoras","E3","Körper: Raumdiagonale rückwärts","Rechnen","einheit"),
(6,1,45,7,"","Sichtweite von einem Turm (Tangente an Erdkugel)","pythagoras","E3","Pythagoras in Figuren (Sachaufgabe)","Sachaufgabe","einheit"),
(6,2,45,8,"","Tabelle a, b, c, p, q, h im rechtwinkligen Dreieck vervollständigen",KE,"–","wie Kap. 6 Nr. 2c","Rechnen","nein"),
(6,2,45,9,"","Neigungswinkel eines Treppengeländers","trigonometrie","E2","Winkel berechnen: aus beiden Katheten mit tan⁻¹","Sachaufgabe","ja"),
(6,2,45,10,"","Mindestdurchmesser eines Baumstamms für einen Balken","pythagoras","E3","Figuren: Rechteckdiagonale im Kreis","Sachaufgabe","einheit"),
(6,2,45,11,"","Seerosenaufgabe: Teichtiefe (Gleichung mit Unbekannter)","pythagoras","E2","Kathete (Gleichung mit Unbekannter in zwei Seiten; Sprosse fehlt)","Sachaufgabe","einheit"),
(6,3,50,12,"a-f","sin, cos, tan mit dem Taschenrechner, auch Winkel zum Wert","trigonometrie","E1","Seite berechnen: Werte mit dem Taschenrechner","Rechnen","einheit"),
(6,3,50,13,"a-b","Tabelle a, b, c, p, q, h (Satzgruppe)",KE,"–","wie Kap. 6 Nr. 2c","Rechnen","nein"),
(6,3,50,14,"a-b","Strecke im Koordinatensystem zeichnerisch messen (Maßstab), Dreieck ergänzen","pythagoras","E1","Abstand zweier Punkte (Sprosse fehlt)","Zeichnen","einheit"),
(6,3,50,14,"c-d","Streckenlänge per Pythagoras prüfen, Dreiecksfläche","pythagoras","E1","Hypotenuse aus Koordinatendifferenzen","Rechnen","einheit"),
(6,3,50,14,"e","Allgemeine Abstandsformel zweier Punkte herleiten","pythagoras","E1","Vorschlag: Sprosse Abstandsformel (Katalog: punkte-und-strecken/abstaende)","Begründen","nein"),
(6,3,50,15,"a-c","Gleichseitiges Dreieck: Winkel, sin α und sin β","trigonometrie","E3","Teildreiecke (Höhe im gleichseitigen Dreieck)","Rechnen","einheit"),
(6,3,50,16,"a-b","Fehlende Seiten und Winkel rechtwinkliger Dreiecke","trigonometrie","E1","Seite und Winkel berechnen (E1/E2)","Rechnen","einheit"),
(6,3,50,17,"","Kürzester Weg auf dem Zylindermantel (Abwicklung)","pythagoras","E3","Körper (Sprosse fehlt)","Sachaufgabe","einheit"),
(6,3,50,18,"","Flächengleiches Quadrat zu Rechteck konstruieren (Höhensatz)",KE,"–","wie Kap. 6 Nr. 2c","Konstruieren","nein"),
# Kap 7 Kreis
(7,1,60,1,"a","Umfang und Fläche aus dem Durchmesser","kreis","E2","Fläche: A aus d; Umfang: u aus d","Rechnen","ja"),
(7,1,60,1,"b","Fläche aus dem Umfang","kreis","E2","r aus u, dann A","Rechnen","einheit"),
(7,1,60,1,"c","Umfang und Fläche einer CD (Maße selbst nehmen)","kreis","E2","Umfang/Fläche mit Dezimalzahlen","Sachaufgabe","einheit"),
(7,1,60,2,"a-e","Aus einer der Größen r, d, u, A die übrigen berechnen","kreis","E2","Fläche: Tabelle r, d, u, A; r aus A","Rechnen","ja"),
(7,1,60,3,"a-c","Markierte Kreisausschnitte: Fläche und Prozentanteil","kreis","E3","Kreisteile: Ausschnittsfläche, Anteil als Prozent","Rechnen","ja"),
(7,1,60,4,"a","Weg der Zeigerspitzen an einem Tag","kreis","E1","Umfang: Sachaufgabe (Umdrehungen)","Sachaufgabe","ja"),
(7,1,60,4,"b","Fläche des Zifferblatts","kreis","E2","Fläche: A aus d","Rechnen","ja"),
(7,1,60,5,"","Beton je Meter Tunnel (Kreisring mal Länge)","kreis","E3","Kreisteile: Kreisring (plus Prismenvolumen)","Sachaufgabe","einheit"),
(7,1,60,6,"","Umfang aus der Fläche","kreis","E2","r aus A, dann u","Rechnen","ja"),
(7,2,55,7,"a-d","Tabelle r, α, Bogenlänge, Ausschnittsfläche (auch rückwärts)","kreis","E3","Kreisteile: Bogenlänge, Ausschnittsfläche, Winkel aus Anteil","Rechnen","einheit"),
(7,2,55,8,"","Zusammengesetzte Fläche aus Halbkreisen","kreis","E2","Fläche: Halbkreis (zusammengesetzt)","Rechnen","einheit"),
(7,2,55,9,"a-b","Laufbahn: gerade Stücke und Mehrlänge der zweiten Bahn","kreis","E1","Umfang: Halbkreisbogen, d aus u","Sachaufgabe","einheit"),
(7,2,55,10,"a-c","Kiesweg und Rasenstreifen als Kreisring: Kosten, Fläche, Anteil","kreis","E3","Kreisteile: Kreisring","Sachaufgabe","einheit"),
(7,2,55,11,"","Bahnradius eines Satelliten aus Geschwindigkeit und Umlaufzeit","kreis","E1","Umfang: r aus u (Sachaufgabe)","Sachaufgabe","einheit"),
(7,2,55,12,"","Flächenverhältnis von Inkreis und Umkreis eines Quadrats","kreis","E2","Fläche (allgemein, mit Pythagoras)","Begründen","einheit"),
(7,2,55,13,"","Mittelpunktswinkel, damit Ausschnitt so groß wie Quadrat (allgemein)","kreis","E3","Kreisteile: Winkel aus Anteil","Umkehrung","einheit"),
# Kap 8 Raumgeometrie
(8,1,45,1,"a","Dreiecksprisma: Volumen und Oberfläche (Hypotenuse per Pythagoras)","koerper","E3","Prisma: Dreiecksgrundfläche, Oberfläche","Rechnen","ja"),
(8,1,45,1,"b","Schrägbild eines stehenden Dreiecksprismas, Teile kennzeichnen","koerper","E1","Schrägbilder (Prisma; Sprosse unsicher)","Zeichnen","einheit"),
(8,1,45,2,"","Zylinderhöhe aus Volumen und Durchmesser","koerper","E4","Zylinder: h aus V","Rechnen","ja"),
(8,1,45,3,"","Quadratische Pyramide aus Grundkante und Seitenkante: V, M, O","pyramide-kegel-kugel","E1","Pyramide: Höhe über Seitenkante (Sprosse unsicher)","Rechnen","einheit"),
(8,1,45,4,"a","Kugel: Volumen und Oberfläche aus r","pyramide-kegel-kugel","E3","Kugel: V aus r, Oberfläche aus r","Rechnen","ja"),
(8,1,45,4,"b","Kugel: Volumen aus Oberfläche","pyramide-kegel-kugel","E3","Kugel: r aus O","Rechnen","ja"),
(8,1,45,5,"a-c","Volumenformel einem Körper zuordnen und nach einer Größe umstellen","lineare-gleichungen","E4","Formeln umstellen","Zuordnen + Umformen","einheit"),
(8,1,45,6,"a-b","Zusammengesetzte Körper (Quader mit Bohrung, Halbzylinderrinne): V und O","koerper","E5","Zusammengesetzt: Restvolumen, Quader und Halbzylinder","Rechnen","einheit"),
(8,1,45,7,"","Wanddicke einer Halbkugelschale aus zwei Oberflächen","pyramide-kegel-kugel","E3","Kugel: Halbkugel, r aus O","Sachaufgabe","einheit"),
(8,2,50,8,"a-d","Zylinder-Tabelle r, h, Mantel, Oberfläche, Volumen (auch rückwärts)","koerper","E4","Zylinder: Mantel, Oberfläche, h aus V, r aus V","Rechnen","einheit"),
(8,2,50,9,"a-c","Kegel-Tabelle r, h, Mantel, Volumen (auch rückwärts)","pyramide-kegel-kugel","E2","Kegel: Mantellinie, Mantel, Volumen","Rechnen","einheit"),
(8,2,50,10,"","Quadervolumen allgemein durch Raumdiagonale und Kante ausdrücken","pythagoras","E3","Körper: Raumdiagonale (allgemein)","Umformen","einheit"),
(8,2,50,11,"","Masse eines Kabels (Hohlzylinder, zwei Dichten)","koerper","E5","Zusammengesetzt: Masse aus Volumen","Sachaufgabe","einheit"),
(8,2,50,12,"","Kreisel als Kugelausschnitt: Volumen und Oberfläche",KE,"–","Vorschlag: Kugelausschnitt nur Zusatz (ZP10 NRW); kein Katalog","Rechnen","nein"),
(8,2,50,13,"","Volumen eines Walmdachs (Prisma plus Pyramidenteile)","pyramide-kegel-kugel","E1","Pyramide in zusammengesetztem Körper","Sachaufgabe","einheit"),
(8,2,50,14,"","Volumen der einem Würfel einbeschriebenen Pyramide (allgemein)","pyramide-kegel-kugel","E1","Pyramide: V aus Grundfläche und Höhe","Rechnen","ja"),
# Kap 9 Prozente und Zinsen
(9,1,45,1,"a-d","Prozenttabelle: Grundwert, Prozentwert oder Prozentsatz gesucht","prozentrechnung","E4","Grundwert: gemischte Aufgaben, erst zuordnen","Rechnen","einheit"),
(9,1,45,2,"a-c","Anteile aus einer Statistiktabelle in Prozent","prozentrechnung","E2","Prozentsatz: aus Sachtext, Ganzes wählen","Sachaufgabe","ja"),
(9,1,45,3,"a","Alte Fotofläche in Prozent der neuen","prozentrechnung","E2","Prozentsatz","Rechnen","einheit"),
(9,1,45,3,"b","Vergrößerung in Prozent","prozentrechnung","E5","Veränderung in Prozent aus zwei Werten","Rechnen","ja"),
(9,1,45,4,"","Festzins und Stufenzins über drei Jahre vergleichen","zinsrechnung","E2","Zinseszins: Guthabentabelle","Sachaufgabe","einheit"),
(9,1,45,5,"","Verdopplungszeit bei Zinseszins, Einfluss des Startkapitals","zinsrechnung","E2","Zinseszins: Laufzeit für Verdopplung (Vorrat)","Rechnen + Begründen","einheit"),
(9,2,45,6,"a-d","Bruch oder Dezimalzahl in Prozent","prozentrechnung","E1","Umwandeln: Dezimalzahl ↔ Prozent","Rechnen","ja"),
(9,2,45,7,"a-c","Prozent in Mittelpunktswinkel per Dreisatz, Faktor 3,6","daten","E3","Anteile darstellen: Prozent → Winkel","Rechnen","ja"),
(9,2,45,7,"d","Art der Zuordnung und Proportionalitätsfaktor benennen",KE,"–","Vorschlag: Zuordnungen (proportional) – nicht in den 16 Einträgen","Begründen","nein"),
(9,2,45,7,"e","Kreisdiagramm zu vier Prozentangaben zeichnen","daten","E3","Anteile darstellen: Sektor zeichnen","Zeichnen","ja"),
(9,2,45,8,"","Zwei Anlageangebote (fest/Stufenzins) vergleichen","zinsrechnung","E2","Zinseszins","Sachaufgabe","einheit"),
(9,2,45,9,"","Preis erst plus 10 %, dann minus 10 %","prozentrechnung","E5","Veränderung: Faktoren nacheinander","Rechnen","einheit"),
(9,2,45,10,"","Laufzeit bis zur Verdreifachung","zinsrechnung","E2","Zinseszins: Laufzeit (Vorrat)","Rechnen","einheit"),
(9,3,40,11,"a-d","Prozentsatz als Dezimalzahl","prozentrechnung","E1","Umwandeln: Dezimalzahl ↔ Prozent","Rechnen","ja"),
(9,3,40,12,"","Sparplan-Tabelle mit jährlicher Einzahlung und Zinsfaktor","zinsrechnung","E2","Zinseszins: Guthabentabelle mit Einzahlung","Rechnen","ja"),
(9,3,40,13,"a-b","Tages- und Monatszinsen","zinsrechnung","E1","Monats- und Tageszinsen","Rechnen","ja"),
(9,3,40,13,"c-e","Zinssatz, Laufzeit, Kapital aus Zinsen (Umkehrungen, unterjährig)","zinsrechnung","E1","Zinsen berechnen: Zinssatz aus Zinsen u. a.","Umkehrung","einheit"),
(9,3,40,14,"a","Skonto: Zahlbetrag","prozentrechnung","E3","Prozentwert: neuer Preis","Rechnen","ja"),
(9,3,40,14,"b","Mehrwertsteuer und Rabatt: Reihenfolge egal?","prozentrechnung","E5","Veränderung: Faktoren vertauschen","Begründen","einheit"),
# Kap 10 Statistik
(10,1,90,1,"a","Notendurchschnitt aus Häufigkeitstabelle","daten","E6","Kenngrößen aus Tabellen: gewichtetes Mittel","Rechnen","ja"),
(10,1,90,1,"b","Boxplot zur Notenverteilung","daten","E5","Boxplot","Zeichnen","einheit"),
(10,1,90,1,"c","Streifendiagramm zur Notenverteilung","daten","E3","Anteile darstellen: Streifen","Zeichnen","ja"),
(10,1,90,2,"a","Mittelwert und Median einer Liste","daten","E4","Kenngrößen: Median, Mittelwert","Rechnen","ja"),
(10,1,90,2,"b","Spannweite, Varianz, Standardabweichung","daten","E4","Kenngrößen aus Listen, Sek II: Standardabweichung","Rechnen","einheit"),
(10,1,90,2,"c","Boxplot","daten","E5","Boxplot","Zeichnen","einheit"),
(10,1,90,2,"d","Säulendiagramm","daten","E2","Säulendiagramm zeichnen","Zeichnen","einheit"),
(10,1,90,3,"","Klasseneinteilung, Histogramm und Streifendiagramm","daten","E6","Klassen (Histogramm; Sprosse unsicher)","Zeichnen","einheit"),
(10,1,90,4,"a","Mittelwert und Median dreier Verteilungen","daten","E4","Kenngrößen","Rechnen","ja"),
(10,1,90,4,"b-d","Besonderheiten, Aussagekraft von Mittel und Median, Ausreißer streichen","daten","E4","Kenngrößen: Aussagen prüfen; Mittelwert nach Änderung","Begründen","einheit"),
(10,1,90,5,"","Mittelwert und Median in Säulendiagramme einzeichnen","daten","E2","Diagramme (Sprosse fehlt)","Zeichnen","einheit"),
(10,1,90,6,"a","Mittlere Abweichung, Varianz, Standardabweichung","daten","E4","Kenngrößen aus Listen, Sek II","Rechnen","einheit"),
(10,1,90,6,"b","Streuungsmaße mit Ergebnissen aus Nr. 4 verbinden","daten","E5","Beurteilen","Begründen","einheit"),
(10,1,90,7,"","Gewichtsangabe für Schokohasen aus Messreihe begründen","daten","E4","Kenngrößen (Mittel/Median wählen)","Begründen","einheit"),
]
